services:
  jenkins:
    build:
      context: ./infrastructure/jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # JNLP agents (optional)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # let Jenkins control Docker
    
    # Run Jenkins as root to bypass docker.sock permission issues
    user: "0:0" 

   # Give pipelines a stable host alias to reach MLflow from their ephemeral build containers
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mlflow:
    build:
      context: ./infrastructure/mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"   # MLflow UI/API
    volumes:
      - mlflow_data:/mlflow

volumes:
  jenkins_home:
  mlflow_data:

